runtime: nodejs14
resources:
  memory_gb: 2
env_variables:
  MY_ENV_VARIABLE: "value"
  PORT : 3333
  MYSQL_HOST : localhost
  MYSQL_USER : root
  MYSQL_PASSWORD : root
  MYSQL_DB : todolist
  SECRET_KEY : X8J6kZ8mD4G58N5M5x7GJ5v77h36Hk75c6n3Bz7R
handlers:
  - url: /api/.*
    script: auto


